--- #YAML:1.0
name:                HTML-FillInForm-Lite
version:             0.031
abstract:            Fills in HTML forms with data
license:             perl
author:              
    - Goro Fuji
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
