---
abstract: 'Lightweight FillInForm module in Pure Perl'
author:
  - 'Goro Fuji (藤 吾郎) <gfuji(at)cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FillInForm-Lite
no_index:
  directory:
    - example
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-HTML-FillInForm-Lite.git
version: 1.11
